### ISSUE TITLE
No more enable ipv4 forwarding?

### ISSUE THREAD

**Issue by bennlich** [sudomesh/exitnode#7]
I noticed that [these lines from the old provision.sh](https://github.com/sudomesh/exitnode/blob/fdd73ff2ddb80d5c31bbcdc07b518cfbb023c60d/provision.sh#L165-L167):

```
# IP Forwarding
sed -i.backup 's/\(.*net.ipv4.ip_forward.*\)/# Enable forwarding for mesh (altered by provisioning script)\nnet.ipv4.ip_forward=1/' /etc/sysctl.conf
echo "1" > /proc/sys/net/ipv4/ip_forward
```

are not in the new `create_exitnode.sh`.

Did they go somewhere else?

**Comment by jhpoelen** [comment]
nice catch . . . did you check the resulting digital ocean exit node?

**Comment by jhpoelen** [comment]
Thanks for checking! Perhaps we should re-introduce this. Please feel free to do so.

**Comment by Juul** [comment]
If /proc/sys/net/ipv4/ip_forward is 1 then we're good.

**Comment by bennlich** [comment]
It might just be a digital ocean droplet thing that this is set to 1 by default.

**Comment by jhpoelen** [comment]
After creating a digital ocean droplet, I noticed that ipv4 forwarding seem to be disabled by default

```
# cat /proc/sys/net/ipv4/ip_forward
0
```

**Comment by jhpoelen** [comment]
Ha! This is a great example of why I should always reproduce before fixing: digital ocean droplets (and probably other systems) have ipv4 ip forwarding disabled by default. I confirmed this by creating a new ubuntu droplet. Then, I ran the create_exitnode script and found that . . . 

```
# cat /proc/sys/net/ipv4/ip_forward
1
```

Turned out that I had refactored the ipv4 forwarding into the sudomesh_gateway configuration at https://github.com/sudomesh/exitnode/commit/ae20153450cefef3b40991da7f76da199532673e .

So, as far as I can tell, the ip forwarding is set by the create exitnode script in the sudomesh_gateway process. 

Please feel free to re-open issue if questions remain.

**Comment by bennlich** [comment]
Ahhhhhh, k. Good checking.
